sources:
    - name: traffic_data_sthlm_db
      schema: staging
      tables: 
        - name: stg_trafikverket_traffic_messages
          identifier: situation_test
        - name: stg_trafikverket_deviation
          identifier: situation_test__deviation
        - name: stg_trafikverket_county_no
          identifier: situation_test__deviation__county_no

        - name: stg_sl_deviations
          identifier: SL_DEVIATIONS
        - name: stg_sl_messages
          identifier: SL_DEVIATIONS__MESSAGE_VARIANTS
        - name: stg_sl_scope_lines
          identifier: SL_DEVIATIONS__SCOPE__LINES
        - name: stg_sl_scope_stop_areas
          identifier: SL_DEVIATIONS__SCOPE__STOP_AREAS
        - name: stg_sl_scope_stop_points
          identifier: SL_DEVIATIONS__SCOPE__STOP_AREAS__STOP_POINTS
        - name: stg_sl_stop_point_info
          identifier: SL_STOP_POINT_INFO